name = "minio"

[namespace.storage]

[namespace.storage.new]
required = ["endpoint", "name", "credential"]
optional = ["work_dir", "location"]

[namespace.storage.op.list]
optional = ["list_mode", "continuation_token"]

[namespace.storage.op.read]
optional = ["offset", "io_callback", "size"]

[namespace.storage.op.stat]
optional = ["object_type"]

[namespace.storage.op.write]
optional = ["content_md5", "content_type", "io_callback"]

[pairs.object_type]
type = "string"
description = "operation object type for stat/delete, could be file or directory"
