name = "minio"

[namespace.storage]

[namespace.storage.new]
required = ["endpoint", "name", "credential"]
optional = ["work_dir", "use_ssl", "region"]

[namespace.storage.op.list]
optional = ["list_mode", "continuation_token", "list_buffer_size"]

[namespace.storage.op.read]
optional = ["offset", "io_callback", "size", "file_version"]

[namespace.storage.op.stat]
optional = ["file_version", "object_type"]

[namespace.storage.op.delete]
optional = ["object_type", "file_version"]

[namespace.storage.op.write]
optional = ["content_md5", "content_type", "io_callback"]

[pairs.use_ssl]
type = "bool"
description = "minio client initalization options"

[pairs.region]
type = "string"
description = "minio client region"

[pairs.file_version]
type = "string"
description = "minio file version"

[pairs.object_type]
type = "string"
description = "operation object type for stat/delete, could be file or directory"

[pairs.list_buffer_size]
type = "int"
description = "one time list buffer size"
